services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: student
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - hotel_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U student -d hotel_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  auth-service:
    build: ./backend/auth-service
    ports:
      - "5002:5002"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://student:12345@db:5432/hotel_db
    networks:
      - app-network

  hotel-service:
    build: ./backend/hotel-service
    ports:
      - "5001:5001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://student:12345@db:5432/hotel_db
    networks:
      - app-network

  reservation-service:
    build: ./backend/reservation-service
    ports:
      - "5003:5003"
    depends_on:
      db:
        condition: service_healthy
      notification-service:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://student:12345@db:5432/hotel_db
    networks:
      - app-network

  notification-service:
    build: ./backend/notification-service
    ports:
      - "5004:5004"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://student:12345@db:5432/hotel_db
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - hotel-service
      - reservation-service
      - notification-service
    environment:
      - REACT_APP_AUTH_URL=http://auth-service:5002
      - REACT_APP_HOTEL_URL=http://hotel-service:5001
      - REACT_APP_RESERVATION_URL=http://reservation-service:5003
      - REACT_APP_NOTIFICATION_URL=http://notification-service:5004

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app-network

  elasticsearch:
    image: elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - app-network

  logstash:
    image: logstash:7.9.3
    volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    networks:
      - app-network

  kibana:
    image: kibana:7.9.3
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  hotel_db_data:
    name: hotel_db_data
