### Test Auth Welcome
GET http://localhost:5002/

### Register User
POST http://localhost:5002/api/auth/register
Content-Type: application/json

{
    "username": "admin@hotel.com",
    "password": "admin123",
    "role": "admin"
}

### Login User
POST http://localhost:5002/api/auth/login
Content-Type: application/json

{
    "username": "admin@hotel.com",
    "password": "admin123"
}