global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:5002']
    metrics_path: '/metrics'

  - job_name: 'hotel-service'
    static_configs:
      - targets: ['hotel-service:5001']
    metrics_path: '/metrics'

  - job_name: 'reservation-service'
    static_configs:
      - targets: ['reservation-service:5003']
    metrics_path: '/metrics'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:5004']
    metrics_path: '/metrics'